services:
    server-test:
        build:
            context: .
            dockerfile: ./docker/test/Dockerfile
        image: thinkphp-php84-server-test
        container_name: thinkphp-php84-server-test
        ports:
            - "8000:80"
            - "8080:8080"
        environment:
            - APP_DEBUG=true
            - DEFAULT_LANG=zh-cn
            - DB_TYPE=mysql
            - DB_HOST=
            - DB_NAME=
            - DB_USER=
            - DB_PASS=
            - DB_PORT=3306
            - DB_CHARSET=utf8mb4
            - REDIS_CLIENT=redis
            - REDIS_HOST=
        restart: always
        networks:
            - thinkphp-network

networks:
    thinkphp-network:
        driver: bridge